In [1]:
#Introduction to NumPy

import numpy as np

In [2]:
np.array([3.2,4,6,5])

array([3.2, 4. , 6. , 5. ])

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
#Understanding Data Types in Python

np.array([1,2,3,4,5],dtype="str")

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [6]:
np.array([3,6,2,3], dtype="float32")

array([3., 6., 2., 3.], dtype=float32)